[package]
name = "hephaestus"
version.workspace = true
edition.workspace = true
publish.workspace = true
default-run = "hephaestus"

[dependencies]
async-channel.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
ide-core.workspace = true
serde.workspace = true
serde_json.workspace = true
terminal.workspace = true
tempfile.workspace = true
tree-sitter.workspace = true
tree-sitter-c.workspace = true
tree-sitter-c-sharp.workspace = true
tree-sitter-go.workspace = true
tree-sitter-java.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-zig.workspace = true

[build-dependencies]
embed-resource.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
ropey.workspace = true
tempfile.workspace = true
terminal = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
